Configuration:
  status: "warn"
  Appenders:
    Console: 
      name: "console"
      PatternLayout:
         pattern: "%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - %m%n"

  Loggers:
    Root:
     level: "info"
     AppenderRef:
      - ref: "console"
